- hosts: javaapp
  become: True
  tasks: 
        - name: install java
          yum:
                  name: java
                  state: present
        - name: set docker network
          docker_network:
                  name: webapp
                  state: present
        - name: 
          docker_container:
                  name: javaapp
                  image: 98ashish/java-app:1.0
                  networks:
                          - name: webapp
